Pheno4D data: https://www.ipb.uni-bonn.de/data/pheno4d/index.html

In [2]:
import open3d as o3d
import numpy as np

In [28]:
import os
import open3d as o3d
mesh = o3d.io.read_triangle_mesh("outs/corn/outputs/00020000_0.ply")
pcd= o3d.io.read_point_cloud("outs/corn/outputs/00020000_0.ply")

In [29]:
o3d.visualization.draw_geometries([mesh])
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 


In [3]:
len(pcd.points)

0

In [9]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[0. 0. 0.]
[0. 0. 0.]


In [ ]:
def normalize(pc):
    pc.translate(-1*pcd.get_min_bound())
    pc.scale(2/np.max(np.array(pc.get_max_bound())),(0,0,0))
    pc.translate(-1/2*pcd.get_max_bound())

In [ ]:
normalize(pcd)

In [ ]:
min_=pcd.get_min_bound()
min_[-1]*=.7
pcd=pcd.crop(o3d.geometry.AxisAlignedBoundingBox(min_,pcd.get_max_bound()))

In [110]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[ 0.06499838 -0.05905672 -0.33952953]
[0.34253657 0.22958471 0.48504618]


In [111]:
o3d.visualization.draw_geometries([pcd])