In [1]:
#import open3d as o3d
from npull.run import Runner
import numpy as np

In [2]:
import os
#pcd = o3d.io.read_point_cloud(os.path.expanduser("~")+"/data/Pheno4d/Maize01/M01_0313_a.txt", format="xyz")

In [8]:
#file=os.path.expanduser("~")+"\data\Pheno4d\Maize01\M01_0313_a.txt"
file="C:\\Users\\tonyb\\Documents\\GitHub\\3DMaizeReconstructionCOMPM\\corn.txt"
print(file)
runner=Runner(file)
runner.train()

C:\Users\tonyb\Documents\GitHub\3DMaizeReconstructionCOMPM\corn.txt
Dataset ConfigTree([('data_dir', 'C:\\Users\tonyb\\data\\Pheno4D\\Maize01'), ('np_data_name', 'carnew1w_norm.npz')])
Data existing. Loading data...
[[ 0.06499838  0.14122907 -0.32616921]
 [ 0.06537265  0.14043465 -0.32385621]
 [ 0.06540563  0.14117458 -0.3248901 ]
 ...
 [ 0.34226555 -0.03971387  0.26547776]
 [ 0.34235015 -0.04352106  0.27983613]
 [ 0.34253657 -0.04337193  0.28120987]]
(230586, 3)
Data bounding box: [ 0.01499838 -0.10905672 -0.38952953] [0.39253657 0.27958471 0.53504618]
NP Load data: End


  6%|▌         | 2498/40000 [00:59<13:57, 44.77it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 12%|█▏        | 4998/40000 [02:03<13:05, 44.57it/s]2024-12-14 16:52:41,738 - outs - INFO - iter:5000 cd_l1 = 0.1881912499666214 lr=0.0009742809738174234 loss=0.1881912499666214


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 19%|█▊        | 7495/40000 [03:09<13:27, 40.24it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 25%|██▍       | 9995/40000 [04:17<12:13, 40.91it/s]2024-12-14 16:54:56,292 - outs - INFO - iter:10000 cd_l1 = 0.18523380160331726 lr=0.0008742820813491108 loss=0.18523380160331726


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 31%|███       | 12497/40000 [05:27<15:08, 30.26it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 37%|███▋      | 14994/40000 [06:36<09:05, 45.87it/s]2024-12-14 16:57:15,372 - outs - INFO - iter:15000 cd_l1 = 0.18537192046642303 lr=0.0007143826681246203 loss=0.18537192046642303


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 44%|████▎     | 17494/40000 [19:35:30<07:00, 53.48it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 50%|████▉     | 19997/40000 [19:36:17<04:50, 68.93it/s]2024-12-15 12:26:56,280 - outs - INFO - iter:20000 cd_l1 = 0.18858154118061066 lr=0.0005201732141536541 loss=0.18858154118061066


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 56%|█████▌    | 22494/40000 [19:37:04<04:49, 60.45it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 62%|██████▏   | 24992/40000 [19:37:50<03:58, 63.04it/s]2024-12-15 12:28:28,938 - outs - INFO - iter:25000 cd_l1 = 0.18755239248275757 lr=0.00032273521654315775 loss=0.18755239248275757


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 69%|██████▊   | 27497/40000 [19:38:35<03:30, 59.53it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 75%|███████▍  | 29996/40000 [19:39:22<02:32, 65.75it/s]2024-12-15 12:30:01,130 - outs - INFO - iter:30000 cd_l1 = 0.19011320173740387 lr=0.0001536668721164906 loss=0.19011320173740387


Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 81%|████████  | 32495/40000 [19:40:06<01:53, 66.05it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([ 0.0150, -0.1091, -0.3895])


 87%|████████▋ | 34738/40000 [19:40:46<2:58:51,  2.04s/it]


KeyboardInterrupt: 