In [1]:
#import open3d as o3d
from npull.run import Runner
import numpy as np

In [2]:
import os
#pcd = o3d.io.read_point_cloud(os.path.expanduser("~")+"/data/Pheno4d/Maize01/M01_0313_a.txt", format="xyz")

In [3]:
file=os.path.expanduser("~")+"\data\Pheno4d\Maize01\M01_0313_a.txt"
#file="C:\\Users\\tonyb\\Documents\\GitHub\\3DMaizeReconstructionCOMPM\\teapot_306.xyz"
print(file)
runner=Runner(file)
runner.train()

C:\Users\tonyb\data\Pheno4d\Maize01\M01_0313_a.txt
Dataset ConfigTree([('data_dir', 'C:\\Users\tonyb\\data\\Pheno4D\\Maize01'), ('np_data_name', 'carnew1w_norm.npz')])
Data existing. Loading data...
[[-115.1937 -737.8151   -4.0411]
 [-115.1822 -737.5399   -4.1691]
 [-115.1296 -738.2211   -3.9881]
 ...
 [  23.9907 -736.7101   -4.2042]
 [  24.2267 -739.8019   -5.1208]
 [  24.279  -739.9107   -5.1493]]
(1554168, 3)
Data bounding box: [-115.2437 -808.1455   -9.2319] [  24.329  -676.4329   58.5188]
NP Load data: End


  6%|▌         | 2496/40000 [00:47<11:33, 54.12it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([-115.2437, -808.1455,   -9.2319])


 12%|█▏        | 4998/40000 [01:40<11:57, 48.81it/s]2024-12-10 18:51:43,111 - outs - INFO - iter:5000 cd_l1 = 0.7973057627677917 lr=0.0009742809738174234 loss=0.7973057627677917


Creating mesh with threshold: 0.0
-1
-1
tensor([-115.2437, -808.1455,   -9.2319])


 19%|█▊        | 7493/40000 [02:31<09:22, 57.81it/s]

Creating mesh with threshold: 0.0
-1
-1
tensor([-115.2437, -808.1455,   -9.2319])


 21%|██▏       | 8543/40000 [03:04<11:20, 46.24it/s]


KeyboardInterrupt: 