Pheno4D data: https://www.ipb.uni-bonn.de/data/pheno4d/index.html

In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import os
corn_pcd = o3d.io.read_point_cloud(os.path.expanduser("~")+"/data/Pheno4d/Maize01/M01_0313_a.txt", format="xyz")
gar_pcd = o3d.io.read_point_cloud("corn.txt", format="xyz")

In [3]:
def normalize(pc):
    pc.translate(-1*pc.get_min_bound())
    pc.scale(2/np.max(np.array(pc.get_max_bound())),(0,0,0))
    pc.translate(-1/2*pc.get_max_bound())

In [4]:
normalize(corn_pcd)

In [5]:
min_=corn_pcd.get_min_bound()
min_[-1]*=.7
corn_pcd=corn_pcd.crop(o3d.geometry.AxisAlignedBoundingBox(min_,corn_pcd.get_max_bound()))

In [6]:
o3d.visualization.draw_geometries([corn_pcd])
o3d.visualization.draw_geometries([gar_pcd])

In [7]:
print(len(corn_pcd.points))
print(len(gar_pcd.points))

230586
230586


In [8]:
print(corn_pcd.get_min_bound())
print(corn_pcd.get_max_bound())
print(gar_pcd.get_min_bound())
print(gar_pcd.get_max_bound())

[ 0.06499838 -0.05905672 -0.33952953]
[0.34253657 0.22958471 0.48504618]
[ 0.06499838 -0.05905672 -0.33952953]
[0.34253657 0.22958471 0.48504618]


In [9]:
def renormalize(pcd, ref):
    normalize(pcd)
    dims=ref.get_max_bound()-ref.get_min_bound()
    pcd.scale(np.max(dims)/2,(0,0,0))

In [10]:
renormalize(corn_pcd,gar_pcd)

In [11]:
print(corn_pcd.get_min_bound())
print(corn_pcd.get_max_bound())
print(gar_pcd.get_min_bound())
print(gar_pcd.get_max_bound())

[-0.13876909 -0.14432072 -0.41228785]
[0.13876909 0.14432072 0.41228785]
[ 0.06499838 -0.05905672 -0.33952953]
[0.34253657 0.22958471 0.48504618]


In [ ]:
#corn_pcd=corn_pcd.voxel_down_sample(voxel_size=0.005)
#print(len(corn_pcd.points))

12713


In [13]:
o3d.visualization.draw_geometries([corn_pcd])

In [ ]:
o3d.io.write_point_cloud("npull/data/corn-voxel-0.ply",corn_pcd,format="ply",write_ascii=True,compressed=False)

True