In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import os
pcd = o3d.io.read_point_cloud(os.path.expanduser("~")+"/data/Pheno4d/Maize01/M01_0313_a.txt", format="xyz")

In [3]:
o3d.visualization.draw_geometries([pcd])

In [4]:
len(pcd.points)

1554168

In [5]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[-115.1937 -808.0955   -9.1819]
[  24.279  -676.4829   58.4688]


In [13]:
def normalize(pc):
    pc.translate(-1*pcd.get_min_bound())
    pc.scale(2/np.max(np.array(pc.get_max_bound())),(0,0,0))
    pc.translate(-1/2*pcd.get_max_bound())

In [14]:
normalize(pcd)

In [15]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[-1.         -0.94364417 -0.48504618]
[1.         0.94364417 0.48504618]


In [16]:
o3d.visualization.draw_geometries([pcd])