Pheno4D data: https://www.ipb.uni-bonn.de/data/pheno4d/index.html

In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [107]:
import os
pcd = o3d.io.read_point_cloud(os.path.expanduser("~")+"/data/Pheno4d/Maize01/M01_0313_a.txt", format="xyz")

In [76]:
o3d.visualization.draw_geometries([pcd])

In [85]:
len(pcd.points)

659856

In [86]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[-117.1654 -808.0452   -7.844 ]
[  23.4455 -668.6772  155.2376]


In [88]:
def normalize(pc):
    pc.translate(-1*pcd.get_min_bound())
    pc.scale(2/np.max(np.array(pc.get_max_bound())),(0,0,0))
    pc.translate(-1/2*pcd.get_max_bound())

In [108]:
normalize(pcd)

In [109]:
min_=pcd.get_min_bound()
min_[-1]*=.7
pcd=pcd.crop(o3d.geometry.AxisAlignedBoundingBox(min_,pcd.get_max_bound()))

In [110]:
print(pcd.get_min_bound())
print(pcd.get_max_bound())

[ 0.06499838 -0.05905672 -0.33952953]
[0.34253657 0.22958471 0.48504618]


In [111]:
o3d.visualization.draw_geometries([pcd])